#+STARTUP: showall

[[https://app.netlify.com/sites/jonathanchu/deploys][https://api.netlify.com/api/v1/badges/3f0f1bda-2338-4eca-afeb-e5db1eeccfc4/deploy-status.svg]]

* jonathanchu.is

My new blogs. Let me show you them.

This is my personal website built with [[https://gohugo.io/  ][Hugo]] and [[https://ox-hugo.scripter.co/][ox-hugo]].

** Prerequisites
Install Hugo

#+BEGIN_SRC shell
brew install hugo
#+END_SRC

In Emacs, install ox-hugo and configure in your init.el config by following the ox-hugo instructions below:
- https://ox-hugo.scripter.co/#installation
- https://ox-hugo.scripter.co/#usage

** Updating the theme

The [[https://github.com/luizdepra/hugo-coder][hugo-coder]] theme is installed as a Hugo module. To check if a newer version is available:

#+BEGIN_SRC shell
go list -m -u all
#+END_SRC

If an update is available, it will appear in brackets after the current version, e.g. ~[v0.0.0-20260115...]~. No brackets means you're on the latest.

To update all modules:

#+BEGIN_SRC shell
hugo mod get -u
#+END_SRC

To update a specific module, specify its path (e.g. the theme):

#+BEGIN_SRC shell
hugo mod get -u github.com/luizdepra/hugo-coder
#+END_SRC

** Local development

Since this is a Hugo site, you can run this locally with this command:

#+BEGIN_SRC shell
hugo server -D
#+END_SRC

After making some changes to ~content-org/content.org~, you can export all valid Hugo subtrees with:

@@html:<kbd>@@C-c C-e H A@@html:</kbd>@@

** Deploying

You can deploy the latest changes by simply pushing to master:

#+BEGIN_SRC shell
git push origin master
#+END_SRC
